### ISSUE TITLE
3.2.0.32459 - Error if target circle drawing enabled

### ISSUE THREAD

**Issue by oorzkws** [PrincessRTFM/PositionalAssistant#4]
Enabling the circle draw setting I get the following error:
```
17:39:01.560 | ERR Exception during raise of "Void draw()"
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PrincessRTFM.PositionalGuide.Plugin.draw() in /work/repo/PositionalGuide/Plugin.cs:line 65
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
```

Settings (without circle enabled, just check the box for the error):
```json
{
  "$type": "PrincessRTFM.PositionalGuide.Configuration, PositionalGuide",
  "Version": 1,
  "Enabled": true,
  "OnlyRenderWhenCentreOnScreen": false,
  "OnlyRenderWhenEndpointOnScreen": false,
  "OnlyRenderWhenEitherEndOnScreen": true,
  "DrawOnPlayers": false,
  "DrawOnSelfOnly": true,
  "DrawTetherLine": true,
  "FlattenTether": true,
  "DrawGuides": [
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false
  ],
  "ExtraDrawRange": 5,
  "MinDrawRange": 0,
  "MaxDrawRange": 255,
  "LineThickness": 3,
  "TetherLengthInner": -1,
  "TetherLengthOuter": -1,
  "TetherColour": {
    "$type": "System.Numerics.Vector4, System.Private.CoreLib",
    "X": 1.0,
    "Y": 1.0,
    "Z": 1.0,
    "W": 0.09803922
  },
  "LineColours": [
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 1.0,
      "Y": 0.0,
      "Z": 0.0,
      "W": 1.0
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 1.0,
      "Y": 0.0,
      "Z": 0.0,
      "W": 1.0
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 0.0,
      "Y": 0.0,
      "Z": 1.0,
      "W": 1.0
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 0.0,
      "Y": 1.0,
      "Z": 0.0,
      "W": 0.09803922
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 0.0,
      "Y": 1.0,
      "Z": 0.0,
      "W": 1.0
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 0.0,
      "Y": 1.0,
      "Z": 0.0,
      "W": 0.09803922
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 0.0,
      "Y": 0.0,
      "Z": 1.0,
      "W": 1.0
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 1.0,
      "Y": 0.0,
      "Z": 0.0,
      "W": 1.0
    },
    {
      "$type": "System.Numerics.Vector4, System.Private.CoreLib",
      "X": 1.0,
      "Y": 1.0,
      "Z": 0.0,
      "W": 1.0
    }
  ]
}
```

**Comment by VariableVixen** [comment]
I don't know how that's happening, considering that [line 65 of that v3.2.0](https://github.com/PrincessRTFM/PositionalAssistant/blob/c1451afde69c47d6383d6128f85bd9336ad511fb/PositionalGuide/Plugin.cs#L65) doesn't actually index anything in the first place. Even if it did, your config is up to date, the only difference against mine is the specific values not the number of them, and I can't reproduce this.

**Comment by oorzkws** [comment]
After compiling debug and adding a try-catch at the supposed error site, I have what looks like a more sane trace.
```
06:16:03.592 | ERR Exception during raise of "Void draw()"
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PrincessRTFM.PositionalGuide.Plugin.draw() in D:\Documents\RiderProjects\PositionalAssistant-master\PositionalGuide\Plugin.cs:line 174
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
 ```
Line 174 for me corresponds to https://github.com/PrincessRTFM/PositionalAssistant/blob/c1451afde69c47d6383d6128f85bd9336ad511fb/PositionalGuide/Plugin.cs#L168

Edit: catch(e) says
06:22:33.219 | WRN [PositionalGuide] Tried to access this.Config.DrawGuides[9] when the array bounds are [0, 8]

**Comment by VariableVixen** [comment]
Which still doesn't make sense, because just prior to that, `arcColouLine` is checked if it exceeds 8, and if so it's `%= 8` which would make it `1` instead... I don't see how this particular error is possible, and I couldn't reproduce it either.

**Comment by VariableVixen** [comment]
Figured it out. `arcColourLine` is negative, so it's being _subtracted_ from the max index. It should be added because it's negative.

**Comment by VariableVixen** [comment]
I'll get the update pushed proper when I'm home, can't do it from my phone

**Comment by oorzkws** [comment]
No hurry, thanks for taking a look

**Comment by VariableVixen** [comment]
It was merged into the live public repo earlier today, so it should be fixed for you now. If not, lemme know and I'll.. start scratching my head again, because that was the only thing I could find, but I'll see what I can do.
